<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ColoniaSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            // Aguascalientes
            ['codigo_postal'=>'20000','colonia'=>'Centro','municipio'=>'Aguascalientes','estado'=>'Aguascalientes'],
            ['codigo_postal'=>'20001','colonia'=>'Los SOFTWARE','municipio'=>'Aguascalientes','estado'=>'Aguascalientes'],
            ['codigo_postal'=>'20100','colonia'=>'Santiago','municipio'=>'Aguascalientes','estado'=>'Aguascalientes'],
            ['codigo_postal'=>'20110','colonia'=>'Jesús García','municipio'=>'Aguascalientes','estado'=>'Aguascalientes'],
            ['codigo_postal'=>'20115','colonia'=>'San Francisco de los Romo','municipio'=>'San Francisco de los Romo','estado'=>'Aguascalientes'],
            ['codigo_postal'=>'20120','colonia'=>'La Estancia','municipio'=>'Aguascalientes','estado'=>'Aguascalientes'],
            ['codigo_postal'=>'20126','colonia'=>'Ojcaliente','municipio'=>'Aguascalientes','estado'=>'Aguascalientes'],
            ['codigo_postal'=>'20127','colonia'=>'Campestre','municipio'=>'Aguascalientes','estado'=>'Aguascalientes'],
            ['codigo_postal'=>'20130','colonia'=>'Arboledas','municipio'=>'Aguascalientes','estado'=>'Aguascalientes'],
            ['codigo_postal'=>'20135','colonia'=>'Revolución','municipio'=>'Aguascalientes','estado'=>'Aguascalientes'],
            ['codigo_postal'=>'20136','colonia'=>'Vista Hermosa','municipio'=>'Aguascalientes','estado'=>'Aguascalientes'],
            ['codigo_postal'=>'20140','colonia'=>'Pocitos','municipio'=>'Aguascalientes','estado'=>'Aguascalientes'],
            ['codigo_postal'=>'20170','colonia'=>'Pabellón de Arteaga','municipio'=>'Pabellón de Arteaga','estado'=>'Aguascalientes'],
            ['codigo_postal'=>'20180','colonia'=>'Rincón de Romos','municipio'=>'Rincón de Romos','estado'=>'Aguascalientes'],
            ['codigo_postal'=>'20200','colonia'=>'Calvillo Centro','municipio'=>'Calvillo','estado'=>'Aguascalientes'],
            ['codigo_postal'=>'20300','colonia'=>'Jesús María Centro','municipio'=>'Jesús María','estado'=>'Aguascalientes'],

            // Baja California
            ['codigo_postal'=>'20000','colonia'=>'Centro','municipio'=>'Mexicali','estado'=>'Baja California'],
            ['codigo_postal'=>'21000','colonia'=>'Centro','municipio'=>'Tijuana','estado'=>'Baja California'],
            ['codigo_postal'=>'21010','colonia'=>'Nueva','municipio'=>'Tijuana','estado'=>'Baja California'],
            ['codigo_postal'=>'21020','colonia'=>'La Esperanza','municipio'=>'Tijuana','estado'=>'Baja California'],
            ['codigo_postal'=>'21030','colonia'=>'Sánchez Taboada','municipio'=>'Tijuana','estado'=>'Baja California'],
            ['codigo_postal'=>'21040','colonia'=>'Hidalgo','municipio'=>'Tijuana','estado'=>'Baja California'],
            ['codigo_postal'=>'21050','colonia'=>'Revolución','municipio'=>'Tijuana','estado'=>'Baja California'],
            ['codigo_postal'=>'21060','colonia'=>'Campestre','municipio'=>'Tijuana','estado'=>'Baja California'],
            ['codigo_postal'=>'21070','colonia'=>'Las Flores','municipio'=>'Tijuana','estado'=>'Baja California'],
            ['codigo_postal'=>'21080','colonia'=>'Infonavit','municipio'=>'Tijuana','estado'=>'Baja California'],
            ['codigo_postal'=>'21100','colonia'=>'Centro','municipio'=>'Ensenada','estado'=>'Baja California'],
            ['codigo_postal'=>'21200','colonia'=>'Centro','municipio'=>'Tecate','estado'=>'Baja California'],
            ['codigo_postal'=>'21300','colonia'=>'Centro','municipio'=>'Playas de Rosarito','estado'=>'Baja California'],
            ['codigo_postal'=>'21360','colonia'=>'Las Gaviotas','municipio'=>'Playas de Rosarito','estado'=>'Baja California'],
            ['codigo_postal'=>'21370','colonia'=>'Foxter','municipio'=>'Playas de Rosarito','estado'=>'Baja California'],

            // Baja California Sur
            ['codigo_postal'=>'23000','colonia'=>'Centro','municipio'=>'La Paz','estado'=>'Baja California Sur'],
            ['codigo_postal'=>'23010','colonia'=>'El Centro','municipio'=>'La Paz','estado'=>'Baja California Sur'],
            ['codigo_postal'=>'23020','colonia'=>'Puerto','municipio'=>'La Paz','estado'=>'Baja California Sur'],
            ['codigo_postal'=>'23060','colonia'=>'Ejido La Paz','municipio'=>'La Paz','estado'=>'Baja California Sur'],
            ['codigo_postal'=>'23070','colonia'=>'Las Conchas','municipio'=>'La Paz','estado'=>'Baja California Sur'],
            ['codigo_postal'=>'23100','colonia'=>'Centro','municipio'=>'San José del Cabo','estado'=>'Baja California Sur'],
            ['codigo_postal'=>'23400','colonia'=>'Centro','municipio'=>'Loreto','estado'=>'Baja California Sur'],
            ['codigo_postal'=>'23500','colonia'=>'Centro','municipio'=>'Ciudad Constitución','estado'=>'Baja California Sur'],

            // Campeche
            ['codigo_postal'=>'24000','colonia'=>'Centro','municipio'=>'Campeche','estado'=>'Campeche'],
            ['codigo_postal'=>'24010','colonia'=>'San Román','municipio'=>'Campeche','estado'=>'Campeche'],
            ['codigo_postal'=>'24020','colonia'=>'Pérez','municipio'=>'Campeche','estado'=>'Campeche'],
            ['codigo_postal'=>'24030','colonia'=>'Fortaleza','municipio'=>'Campeche','estado'=>'Campeche'],
            ['codigo_postal'=>'24040','colonia'=>'Gavias','municipio'=>'Campeche','estado'=>'Campeche'],
            ['codigo_postal'=>'24100','colonia'=>'Centro','municipio'=>'Ciudad del Carmen','estado'=>'Campeche'],
            ['codigo_postal'=>'24150','colonia'=>'Nueva','municipio'=>'Ciudad del Carmen','estado'=>'Campeche'],
            ['codigo_postal'=>'24190','colonia'=>'Poblado','municipio'=>'Ciudad del Carmen','estado'=>'Campeche'],

            // Chiapas
            ['codigo_postal'=>'29000','colonia'=>'Centro','municipio'=>'Tuxtla Gutiérrez','estado'=>'Chiapas'],
            ['codigo_postal'=>'29010','colonia'=>'Modelo','municipio'=>'Tuxtla Gutiérrez','estado'=>'Chiapas'],
            ['codigo_postal'=>'29020','colonia'=>'Las Flores','municipio'=>'Tuxtla Gutiérrez','estado'=>'Chiapas'],
            ['codigo_postal'=>'29030','colonia'=>'Américas','municipio'=>'Tuxtla Gutiérrez','estado'=>'Chiapas'],
            ['codigo_postal'=>'29040','colonia'=>'Cañadas','municipio'=>'Tuxtla Gutiérrez','estado'=>'Chiapas'],
            ['codigo_postal'=>'29050','colonia'=>'Los Ángeles','municipio'=>'Tuxtla Gutiérrez','estado'=>'Chiapas'],
            ['codigo_postal'=>'29060','colonia'=>'México','municipio'=>'Tuxtla Gutiérrez','estado'=>'Chiapas'],
            ['codigo_postal'=>'29070','colonia'=>'Patria','municipio'=>'Tuxtla Gutiérrez','estado'=>'Chiapas'],
            ['codigo_postal'=>'29090','colonia'=>'San Julián','municipio'=>'Tuxtla Gutiérrez','estado'=>'Chiapas'],
            ['codigo_postal'=>'29100','colonia'=>'San Cristóbal Centro','municipio'=>'San Cristóbal de las Casas','estado'=>'Chiapas'],
            ['codigo_postal'=>'29120','colonia'=>'Santo Domingo','municipio'=>'San Cristóbal de las Casas','estado'=>'Chiapas'],
            ['codigo_postal'=>'29130','colonia'=>'Las Rosas','municipio'=>'San Cristóbal de las Casas','estado'=>'Chiapas'],
            ['codigo_postal'=>'29200','colonia'=>'Centro','municipio'=>'Comitán de Domínguez','estado'=>'Chiapas'],
            ['codigo_postal'=>'29300','colonia'=>'Centro','municipio'=>'Tapachula','estado'=>'Chiapas'],
            ['codigo_postal'=>'29310','colonia'=>'La Libertad','municipio'=>'Tapachula','estado'=>'Chiapas'],
            ['codigo_postal'=>'29400','colonia'=>'Centro','municipio'=>'Palenque','estado'=>'Chiapas'],

            // Chihuahua
            ['codigo_postal'=>'31000','colonia'=>'Centro','municipio'=>'Chihuahua','estado'=>'Chihuahua'],
            ['codigo_postal'=>'31010','colonia'=>'San Felipe','municipio'=>'Chihuahua','estado'=>'Chihuahua'],
            ['codigo_postal'=>'31020','colonia'=>'Mirador','municipio'=>'Chihuahua','estado'=>'Chihuahua'],
            ['codigo_postal'=>'31030','colonia'=>'Los Nogales','municipio'=>'Chihuahua','estado'=>'Chihuahua'],
            ['codigo_postal'=>'31040','colonia'=>'Vista Hermosa','municipio'=>'Chihuahua','estado'=>'Chihuahua'],
            ['codigo_postal'=>'31050','colonia'=>'Las Américas','municipio'=>'Chihuahua','estado'=>'Chihuahua'],
            ['codigo_postal'=>'31060','colonia'=>'Pedro Infante','municipio'=>'Chihuahua','estado'=>'Chihuahua'],
            ['codigo_postal'=>'31070','colonia'=>'Santa Bárbara','municipio'=>'Chihuahua','estado'=>'Chihuahua'],
            ['codigo_postal'=>'31090','colonia'=>'Nuevo Chihuahua','municipio'=>'Chihuahua','estado'=>'Chihuahua'],
            ['codigo_postal'=>'31100','colonia'=>'Santa Rosa','municipio'=>'Chihuahua','estado'=>'Chihuahua'],
            ['codigo_postal'=>'31200','colonia'=>'Centro','municipio'=>'Cuauhtémoc','estado'=>'Chihuahua'],
            ['codigo_postal'=>'31300','colonia'=>'Centro','municipio'=>'Delicias','estado'=>'Chihuahua'],
            ['codigo_postal'=>'31400','colonia'=>'Centro','municipio'=>'Nuevo Casas Grandes','estado'=>'Chihuahua'],
            ['codigo_postal'=>'31500','colonia'=>'Centro','municipio'=>'Camargo','estado'=>'Chihuahua'],
            ['codigo_postal'=>'31600','colonia'=>'Centro','municipio'=>'Jiménez','estado'=>'Chihuahua'],
            ['codigo_postal'=>'32000','colonia'=>'Centro','municipio'=>'Juárez','estado'=>'Chihuahua'],
            ['codigo_postal'=>'32100','colonia'=>'Pronaf','municipio'=>'Juárez','estado'=>'Chihuahua'],
            ['codigo_postal'=>'32200','colonia'=>'Azcapotzalco','municipio'=>'Juárez','estado'=>'Chihuahua'],
            ['codigo_postal'=>'32300','colonia'=>'Díaz Ordaz','municipio'=>'Juárez','estado'=>'Chihuahua'],
            ['codigo_postal'=>'32310','colonia'=>'Santa Fe','municipio'=>'Juárez','estado'=>'Chihuahua'],
            ['codigo_postal'=>'32330','colonia'=>'Las Misiones','municipio'=>'Juárez','estado'=>'Chihuahua'],
            ['codigo_postal'=>'32400','colonia'=>'Progreso','municipio'=>'Juárez','estado'=>'Chihuahua'],
            ['codigo_postal'=>'32410','colonia'=>'Los Prados','municipio'=>'Juárez','estado'=>'Chihuahua'],
            ['codigo_postal'=>'32420','colonia'=>'Las Américas','municipio'=>'Juárez','estado'=>'Chihuahua'],
            ['codigo_postal'=>'32470','colonia'=>'Independencia','municipio'=>'Juárez','estado'=>'Chihuahua'],
            ['codigo_postal'=>'32480','colonia'=>'Cerro Bola','municipio'=>'Juárez','estado'=>'Chihuahua'],
            ['codigo_postal'=>'32500','colonia'=>'Campestre','municipio'=>'Juárez','estado'=>'Chihuahua'],
            ['codigo_postal'=>'32530','colonia'=>'Del Valle','municipio'=>'Juárez','estado'=>'Chihuahua'],
            ['codigo_postal'=>'32540','colonia'=>'Valle de Juárez','municipio'=>'Juárez','estado'=>'Chihuahua'],
            ['codigo_postal'=>'32570','colonia'=>'Los Alpes','municipio'=>'Juárez','estado'=>'Chihuahua'],
            ['codigo_postal'=>'32600','colonia'=>'Lomas de Juárez','municipio'=>'Juárez','estado'=>'Chihuahua'],
            ['codigo_postal'=>'32610','colonia'=>'Montebello','municipio'=>'Juárez','estado'=>'Chihuahua'],
            ['codigo_postal'=>'32620','colonia'=>'Loma Bonita','municipio'=>'Juárez','estado'=>'Chihuahua'],
            ['codigo_postal'=>'32630','colonia'=>'Cumbres','municipio'=>'Juárez','estado'=>'Chihuahua'],
            ['codigo_postal'=>'32640','colonia'=>'Puesta del Sol','municipio'=>'Juárez','estado'=>'Chihuahua'],
            ['codigo_postal'=>'32650','colonia'=>'El Palomar','municipio'=>'Juárez','estado'=>'Chihuahua'],
            ['codigo_postal'=>'32660','colonia'=>'Las Torres','municipio'=>'Juárez','estado'=>'Chihuahua'],
            ['codigo_postal'=>'32670','colonia'=>'Villa Bonita','municipio'=>'Juárez','estado'=>'Chihuahua'],
            ['codigo_postal'=>'32680','colonia'=>'La Silla','municipio'=>'Juárez','estado'=>'Chihuahua'],
            ['codigo_postal'=>'32690','colonia'=>'Villas del Sol','municipio'=>'Juárez','estado'=>'Chihuahua'],
            ['codigo_postal'=>'32700','colonia'=>'Puerta de Hierro','municipio'=>'Juárez','estado'=>'Chihuahua'],
            ['codigo_postal'=>'32710','colonia'=>'El Lago','municipio'=>'Juárez','estado'=>'Chihuahua'],
            ['codigo_postal'=>'32720','colonia'=>'Portón de Hierro','municipio'=>'Juárez','estado'=>'Chihuahua'],
            ['codigo_postal'=>'32730','colonia'=>'Los Viñedos','municipio'=>'Juárez','estado'=>'Chihuahua'],
            ['codigo_postal'=>'32740','colonia'=>'Real del Lago','municipio'=>'Juárez','estado'=>'Chihuahua'],
            ['codigo_postal'=>'32750','colonia'=>'El Campanario','municipio'=>'Juárez','estado'=>'Chihuahua'],
            ['codigo_postal'=>'32760','colonia'=>'Bosques de San Sebastián','municipio'=>'Juárez','estado'=>'Chihuahua'],
            ['codigo_postal'=>'32770','colonia'=>'Haciendas del Valle','municipio'=>'Juárez','estado'=>'Chihuahua'],
            ['codigo_postal'=>'32780','colonia'=>'Del Refugio','municipio'=>'Juárez','estado'=>'Chihuahua'],
            ['codigo_postal'=>'32790','colonia'=>'Los Parques','municipio'=>'Juárez','estado'=>'Chihuahua'],

            // Ciudad de México
            ['codigo_postal'=>'06000','colonia'=>'Centro','municipio'=>'Cuauhtémoc','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06010','colonia'=>'Roma Norte','municipio'=>'Cuauhtémoc','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06020','colonia'=>'Juárez','municipio'=>'Cuauhtémoc','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06030','colonia'=>'Cuauhtémoc','municipio'=>'Cuauhtémoc','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06040','colonia'=>'Condesa','municipio'=>'Cuauhtémoc','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06050','colonia'=>'Escandón','municipio'=>'Cuauhtémoc','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06060','colonia'=>'Hipódromo','municipio'=>'Cuauhtémoc','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06070','colonia'=>'Hipódromo Condesa','municipio'=>'Cuauhtémoc','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06080','colonia'=>'San Rafael','municipio'=>'Cuauhtémoc','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06090','colonia'=>'Santa María la Ribera','municipio'=>'Cuauhtémoc','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06100','colonia'=>'Doctores','municipio'=>'Cuauhtémoc','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06140','colonia'=>'Obrera','municipio'=>'Cuauhtémoc','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06150','colonia'=>'Roma Sur','municipio'=>'Cuauhtémoc','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06160','colonia'=>'Del Valle Centro','municipio'=>'Benito Juárez','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06170','colonia'=>'Del Valle Norte','municipio'=>'Benito Juárez','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06180','colonia'=>'Del Valle Sur','municipio'=>'Benito Juárez','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06190','colonia'=>'Américas','municipio'=>'Benito Juárez','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06200','colonia'=>'Portales','municipio'=>'Benito Juárez','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06210','colonia'=>'Acacias','municipio'=>'Benito Juárez','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06220','colonia'=>'Narvarte','municipio'=>'Benito Juárez','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06230','colonia'=>'Eje 5','municipio'=>'Benito Juárez','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06240','colonia'=>'Vista Alegre','municipio'=>'Benito Juárez','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06250','colonia'=>'Sinatel','municipio'=>'Benito Juárez','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06260','colonia'=>'Las Américas','municipio'=>'Benito Juárez','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06270','colonia'=>'Ciudad de los Deportes','municipio'=>'Benito Juárez','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06280','colonia'=>'Miravalle','municipio'=>'Benito Juárez','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06290','colonia'=>'Xoco','municipio'=>'Benito Juárez','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06300','colonia'=>'Santa María la Ribera','municipio'=>'Cuauhtémoc','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06350','colonia'=>'San Simón Tolnáhuac','municipio'=>'Cuauhtémoc','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06400','colonia'=>'Centro Histórico','municipio'=>'Cuauhtémoc','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06430','colonia'=>'Artes Gráficas','municipio'=>'Cuauhtémoc','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06440','colonia'=>'San Juan Moyotlán','municipio'=>'Cuauhtémoc','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06450','colonia'=>'Santa María Tequixquiac','municipio'=>'Cuauhtémoc','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06460','colonia'=>'San Pablo Tequixquiac','municipio'=>'Cuauhtémoc','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06470','colonia'=>'San Miguel Chapultepec','municipio'=>'Miguel Hidalgo','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06500','colonia'=>'Polanco','municipio'=>'Miguel Hidalgo','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06510','colonia'=>'Polanco II Sección','municipio'=>'Miguel Hidalgo','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06520','colonia'=>'Polanco III Sección','municipio'=>'Miguel Hidalgo','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06530','colonia'=>'Polanco IV Sección','municipio'=>'Miguel Hidalgo','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06600','colonia'=>'Las Lomas','municipio'=>'Miguel Hidalgo','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06700','colonia'=>'Chapultepec','municipio'=>'Miguel Hidalgo','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06760','colonia'=>'Verónica Anzures','municipio'=>'Miguel Hidalgo','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06770','colonia'=>'Miguel Hidalgo','municipio'=>'Miguel Hidalgo','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06780','colonia'=>'San Joaquín','municipio'=>'Miguel Hidalgo','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06790','colonia'=>'Tacubaya','municipio'=>'Miguel Hidalgo','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06800','colonia'=>'Anzures','municipio'=>'Miguel Hidalgo','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06810','colonia'=>'Bellavista','municipio'=>'Miguel Hidalgo','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06820','colonia'=>'Cuauthémoc','municipio'=>'Miguel Hidalgo','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06830','colonia'=>'H ponds','municipio'=>'Miguel Hidalgo','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06840','colonia'=>'Pegásos','municipio'=>'Miguel Hidalgo','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06850','colonia'=>'Santa Fe','municipio'=>'Miguel Hidalgo','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06860','colonia'=>'Nuevo Polanco','municipio'=>'Miguel Hidalgo','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06870','colonia'=>'Lomas de Chapultepec','municipio'=>'Miguel Hidalgo','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06880','colonia'=>'Las Lomas','municipio'=>'Miguel Hidalgo','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06890','colonia'=>'Hermosillo','municipio'=>'Miguel Hidalgo','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'06900','colonia'=>'Lomas de Virreyes','municipio'=>'Miguel Hidalgo','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07000','colonia'=>'Centro','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07010','colonia'=>'Guadalupe Tepeyac','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07020','colonia'=>'Tepeyac Insurgentes','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07030','colonia'=>'San Juan de Aragón','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07040','colonia'=>'González Suárez','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07050','colonia'=>'Jardín Balbuena','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07060','colonia'=>'Vallejo','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07070','colonia'=>'Industrial Vallejo','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07080','colonia'=>'Nueva Atzacoalco','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07090','colonia'=>'Ampliación Petén','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07100','colonia'=>'Fidel Velázquez','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07110','colonia'=>'San Juan de Aragón VII Sección','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07120','colonia'=>'San Juan de Aragón VI Sección','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07130','colonia'=>'Santos','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07140','colonia'=>'Cuchilla Pantitlán','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07150','colonia'=>'Dr. Martín','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07160','colonia'=>'Maximino Avila Camacho','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07170','colonia'=>'Granjas Modernas','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07180','colonia'=>'Nueva Industrial Valentin Gómez','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07190','colonia'=>'Tepetates','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07200','colonia'=>'San Felipe de Jesús','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07210','colonia'=>'Artesanos','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07220','colonia'=>'Cuchilla del Faisán','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07230','colonia'=>'La Pastora','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07240','colonia'=>'Ctec','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07250','colonia'=>'San José de Aragón','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07260','colonia'=>'Jardín Balbuena','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07270','colonia'=>'Clavería','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07280','colonia'=>'Del Parque','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07290','colonia'=>'Ex Hipódromo de Balbuena','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07300','colonia'=>'Del Gaznú','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07310','colonia'=>'INFONAVIT','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07320','colonia'=>'La Quinta','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07330','colonia'=>'Martín Carrera','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07340','colonia'=>'Ticoman','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07350','colonia'=>'La Purísima Tacubaya','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07360','colonia'=>'Mártires de Tacubaya','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07370','colonia'=>'Reforma', 'municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07380','colonia'=>'San José Tepeyac','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07390','colonia'=>'San Luis Tlaxialtemalco','municipio'=>'Gustavo A. Madero','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07400','colonia'=>'Deportivo','municipio'=>'Iztacalco','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07410','colonia'=>'San Miguel','municipio'=>'Iztacalco','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07420','colonia'=>'Peñón de los Baños','municipio'=>'Iztacalco','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07430','colonia'=>'Santa Cruz','municipio'=>'Iztacalco','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07440','colonia'=>'Coyoacán','municipio'=>'Iztacalco','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07450','colonia'=>'Agrícola Oriental','municipio'=>'Iztacalco','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07460','colonia'=>'Pantitlán','municipio'=>'Iztacalco','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07470','colonia'=>'San Francisco Javier','municipio'=>'Iztacalco','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07480','colonia'=>'San Lucas','municipio'=>'Iztacalco','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07490','colonia'=>'Santa Anita','municipio'=>'Iztacalco','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07500','colonia'=>'Iztacalco','municipio'=>'Iztacalco','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07510','colonia'=>'Ampliación Iztacalco','municipio'=>'Iztacalco','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07520','colonia'=>'San Pedro Iztacalco','municipio'=>'Iztacalco','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07530','colonia'=>'Santa Anita Zacatlalco','municipio'=>'Iztacalco','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07540','colonia'=>'Lomas de Zaragoza','municipio'=>'Iztacalco','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07550','colonia'=>'San Miguel Topilejo','municipio'=>'Iztacalco','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07560','colonia'=>'San Pedro Atocpan','municipio'=>'Milpa Alta','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07570','colonia'=>'Santa Ana Tlacotenco','municipio'=>'Milpa Alta','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07580','colonia'=>'San Pablo Oztotepec','municipio'=>'Milpa Alta','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07590','colonia'=>'San Juan Tepenahuac','municipio'=>'Milpa Alta','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07600','colonia'=>'San Agustín Ohtenco','municipio'=>'Milpa Alta','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07610','colonia'=>'San Pablo Atla','municipio'=>'Milpa Alta','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07620','colonia'=>'Tlayacapan','municipio'=>'Milpa Alta','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07630','colonia'=>'San Juan俗ra','municipio'=>'Milpa Alta','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07640','colonia'=>'Santa Inés Yatzeche','municipio'=>'Milpa Alta','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07650','colonia'=>'San Juan Econahuac','municipio'=>'Milpa Alta','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07660','colonia'=>'San Pedro Actipac','municipio'=>'Milpa Alta','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07670','colonia'=>'San Mateo Xalpa','municipio'=>'Milpa Alta','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07680','colonia'=>'Santa Cruz Xoxocotlán','municipio'=>'Milpa Alta','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07690','colonia'=>'San Agustín Ohtenco','municipio'=>'Milpa Alta','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07700','colonia'=>'Coyoacán Centro','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07710','colonia'=>'Guadalupe','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07720','colonia'=>'San Pablo','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07730','colonia'=>'Santa Catarina','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07740','colonia'=>'Los Reyes','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07750','colonia'=>'Santa Lucía','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07760','colonia'=>'La Concepción','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07770','colonia'=>'San Sebastián','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07780','colonia'=>'Santo Domingo','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07790','colonia'=>'San Ángel','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07800','colonia'=>'Chimalistac','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07810','colonia'=>'Del Carmen','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07820','colonia'=>'San Ángel Sur','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07830','colonia'=>'Remedios','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07840','colonia'=>'El Rosedal','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07850','colonia'=>'Pedregal de San Ángel','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07860','colonia'=>'Tres Picos','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07870','colonia'=>'Oxtopulco','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07880','colonia'=>'Pablo Sidar','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07890','colonia'=>'Camacho','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07900','colonia'=>'Tizapán','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07910','colonia'=>'San Diego Churubusco','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07920','colonia'=>'Xoco','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07930','colonia'=>'Villa Olímpica','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07940','colonia'=>'Portales del Pedregal','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07950','colonia'=>'Centro de Coyoacán','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07960','colonia'=>'Viveros','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07970','colonia'=>'Héroes de Padierna','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07980','colonia'=>'Las Campanas','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'07990','colonia'=>'Fuentes del Pedregal','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'08000','colonia'=>'Centro','municipio'=>'Iztapalapa','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'08100','colonia'=>'Santiago Acahualtepec','municipio'=>'Iztapalapa','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'08200','colonia'=>'Nueva','municipio'=>'Iztapalapa','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'08300','colonia'=>'San Andrés Tomatlán','municipio'=>'Iztapalapa','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'08400','colonia'=>'San Juanico','municipio'=>'Iztapalapa','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'08500','colonia'=>'Santa Cruz','municipio'=>'Iztapalapa','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'08600','colonia'=>'San Lorenzo Tezonco','municipio'=>'Iztapalapa','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'08700','colonia'=>'San Gregorio Atlapulco','municipio'=>'Iztapalapa','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'08800','colonia'=>'San Martín Xochinahuac','municipio'=>'Iztapalapa','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'08900','colonia'=>'Santa María Tomatlán','municipio'=>'Iztapalapa','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'09000','colonia'=>'Centro','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'09010','colonia'=>'Santa Úrsula','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'09020','colonia'=>'La Candelaria','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'09030','colonia'=>'Santa María Nativitas','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'09040','colonia'=>'San Pablo Tepetlapa','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'09050','colonia'=>'San Baltazar','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'09060','colonia'=>'San Pedro','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'09070','colonia'=>'Santa Úrsula Coapa','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'09080','colonia'=>'San Luis Tlaxialtemalco','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'09090','colonia'=>'San Juan','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'09100','colonia'=>'San Pablo','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'09200','colonia'=>'Santa Cruz','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'09300','colonia'=>'San Lucas','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'09400','colonia'=>'Santa María','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'09500','colonia'=>'San Mateo','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'09600','colonia'=>'Santa Catarina','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'09700','colonia'=>'San Agustín','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'09800','colonia'=>'San Jerónimo','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'09900','colonia'=>'San Nicolás','municipio'=>'Coyoacán','estado'=>'Ciudad de México'],

            // Coahuila
            ['codigo_postal'=>'25000','colonia'=>'Centro','municipio'=>'Saltillo','estado'=>'Coahuila'],
            ['codigo_postal'=>'25010','colonia'=>'Reforma','municipio'=>'Saltillo','estado'=>'Coahuila'],
            ['codigo_postal'=>'25020','colonia'=>'Nazario S. Ortiz','municipio'=>'Saltillo','estado'=>'Coahuila'],
            ['codigo_postal'=>'25030','colonia'=>'Recta a Matehuala','municipio'=>'Saltillo','estado'=>'Coahuila'],
            ['codigo_postal'=>'25040','colonia'=>'Fundadores','municipio'=>'Saltillo','estado'=>'Coahuila'],
            ['codigo_postal'=>'25050','colonia'=>'Las Flores','municipio'=>'Saltillo','estado'=>'Coahuila'],
            ['codigo_postal'=>'25060','colonia'=>'Villatoro','municipio'=>'Saltillo','estado'=>'Coahuila'],
            ['codigo_postal'=>'25070','colonia'=>'Mineral','municipio'=>'Saltillo','estado'=>'Coahuila'],
            ['codigo_postal'=>'25080','colonia'=>'INFONAVIT','municipio'=>'Saltillo','estado'=>'Coahuila'],
            ['codigo_postal'=>'25090','colonia'=>'Villas del Valle','municipio'=>'Saltillo','estado'=>'Coahuila'],
            ['codigo_postal'=>'25100','colonia'=>'Artesanos','municipio'=>'Saltillo','estado'=>'Coahuila'],
            ['codigo_postal'=>'25200','colonia'=>'Centro','municipio'=>'Torreón','estado'=>'Coahuila'],
            ['codigo_postal'=>'25280','colonia'=>'Buenos Aires','municipio'=>'Torreón','estado'=>'Coahuila'],
            ['codigo_postal'=>'25300','colonia'=>'Centro','municipio'=>'Monclova','estado'=>'Coahuila'],
            ['codigo_postal'=>'25400','colonia'=>'Centro','municipio'=>'Piedras Negras','estado'=>'Coahuila'],
            ['codigo_postal'=>'25500','colonia'=>'Centro','municipio'=>'Acuña','estado'=>'Coahuila'],
            ['codigo_postal'=>'25600','colonia'=>'Centro','municipio'=>'Matamoros','estado'=>'Coahuila'],
            ['codigo_postal'=>'25700','colonia'=>'Centro','municipio'=>'Sabinas','estado'=>'Coahuila'],
            ['codigo_postal'=>'25800','colonia'=>'Centro','municipio'=>'Frontera','estado'=>'Coahuila'],
            ['codigo_postal'=>'25900','colonia'=>'Centro','municipio'=>'Monclova','estado'=>'Coahuila'],

            // Colima
            ['codigo_postal'=>'28000','colonia'=>'Centro','municipio'=>'Colima','estado'=>'Colima'],
            ['codigo_postal'=>'28010','colonia'=>'Nueva','municipio'=>'Colima','estado'=>'Colima'],
            ['codigo_postal'=>'28020','colonia'=>'San Sebastián','municipio'=>'Colima','estado'=>'Colima'],
            ['codigo_postal'=>'28030','colonia'=>'San Miguel','municipio'=>'Colima','estado'=>'Colima'],
            ['codigo_postal'=>'28040','colonia'=>'Elhuixtle','municipio'=>'Colima','estado'=>'Colima'],
            ['codigo_postal'=>'28050','colonia'=>'La Aurora','municipio'=>'Colima','estado'=>'Colima'],
            ['codigo_postal'=>'28060','colonia'=>'La Victoria','municipio'=>'Colima','estado'=>'Colima'],
            ['codigo_postal'=>'28070','colonia'=>'INFONAVIT','municipio'=>'Colima','estado'=>'Colima'],
            ['codigo_postal'=>'28080','colonia'=>'Los Cactus','municipio'=>'Colima','estado'=>'Colima'],
            ['codigo_postal'=>'28090','colonia'=>'Las Fuentes','municipio'=>'Colima','estado'=>'Colima'],
            ['codigo_postal'=>'28100','colonia'=>'Centro','municipio'=>'Manzanillo','estado'=>'Colima'],
            ['codigo_postal'=>'28200','colonia'=>'Centro','municipio'=>'Tecomán','estado'=>'Colima'],
            ['codigo_postal'=>'28300','colonia'=>'Centro','municipio'=>'Villa de Álvarez','estado'=>'Colima'],

            // Durango
            ['codigo_postal'=>'34000','colonia'=>'Centro','municipio'=>'Durango','estado'=>'Durango'],
            ['codigo_postal'=>'34010','colonia'=>'Nicolás Bravo','municipio'=>'Durango','estado'=>'Durango'],
            ['codigo_postal'=>'34020','colonia'=>'Madero','municipio'=>'Durango','estado'=>'Durango'],
            ['codigo_postal'=>'34030','colonia'=>'San José','municipio'=>'Durango','estado'=>'Durango'],
            ['codigo_postal'=>'34040','colonia'=>'Reforma','municipio'=>'Durango','estado'=>'Durango'],
            ['codigo_postal'=>'34050','colonia'=>'Libertad','municipio'=>'Durango','estado'=>'Durango'],
            ['codigo_postal'=>'34060','colonia'=>'Independencia','municipio'=>'Durango','estado'=>'Durango'],
            ['codigo_postal'=>'34070','colonia'=>'Aldama','municipio'=>'Durango','estado'=>'Durango'],
            ['codigo_postal'=>'34080','colonia'=>'Centro','municipio'=>'Durango','estado'=>'Durango'],
            ['codigo_postal'=>'34090','colonia'=>'6 de Junio','municipio'=>'Durango','estado'=>'Durango'],
            ['codigo_postal'=>'34100','colonia'=>'Hidalgo','municipio'=>'Durango','estado'=>'Durango'],
            ['codigo_postal'=>'34200','colonia'=>'Centro','municipio'=>'Gómez Palacio','estado'=>'Durango'],
            ['codigo_postal'=>'34300','colonia'=>'Centro','municipio'=>'Lerdo','estado'=>'Durango'],

            // Estado de México
            ['codigo_postal'=>'50000','colonia'=>'Centro','municipio'=>'Toluca','estado'=>'Estado de México'],
            ['codigo_postal'=>'50010','colonia'=>'San Bernardino','municipio'=>'Toluca','estado'=>'Estado de México'],
            ['codigo_postal'=>'50020','colonia'=>'San Sebastián','municipio'=>'Toluca','estado'=>'Estado de México'],
            ['codigo_postal'=>'50030','colonia'=>'San Miguel','municipio'=>'Toluca','estado'=>'Estado de México'],
            ['codigo_postal'=>'50040','colonia'=>'San Pablo','municipio'=>'Toluca','estado'=>'Estado de México'],
            ['codigo_postal'=>'50050','colonia'=>'Santa Ana','municipio'=>'Toluca','estado'=>'Estado de México'],
            ['codigo_postal'=>'50060','colonia'=>'Santa Cruz','municipio'=>'Toluca','estado'=>'Estado de México'],
            ['codigo_postal'=>'50070','colonia'=>'Santiago','municipio'=>'Toluca','estado'=>'Estado de México'],
            ['codigo_postal'=>'50080','colonia'=>'Santo Tomás','municipio'=>'Toluca','estado'=>'Estado de México'],
            ['codigo_postal'=>'50090','colonia'=>'Tollocan','municipio'=>'Toluca','estado'=>'Estado de México'],
            ['codigo_postal'=>'50100','colonia'=>'Xochitenco','municipio'=>'Toluca','estado'=>'Estado de México'],
            ['codigo_postal'=>'50110','colonia'=>'San Mateo','municipio'=>'Toluca','estado'=>'Estado de México'],
            ['codigo_postal'=>'50120','colonia'=>'San Pedro','municipio'=>'Toluca','estado'=>'Estado de México'],
            ['codigo_postal'=>'50130','colonia'=>'Santa María','municipio'=>'Toluca','estado'=>'Estado de México'],
            ['codigo_postal'=>'50140','colonia'=>'San Juan','municipio'=>'Toluca','estado'=>'Estado de México'],
            ['codigo_postal'=>'50150','colonia'=>'Santa Lucía','municipio'=>'Toluca','estado'=>'Estado de México'],
            ['codigo_postal'=>'50160','colonia'=>'Santa Verónica','municipio'=>'Toluca','estado'=>'Estado de México'],
            ['codigo_postal'=>'50170','colonia'=>'Vista Hermosa','municipio'=>'Toluca','estado'=>'Estado de México'],
            ['codigo_postal'=>'50180','colonia'=>'Américas','municipio'=>'Toluca','estado'=>'Estado de México'],
            ['codigo_postal'=>'50190','colonia'=>'INFONAVIT','municipio'=>'Toluca','estado'=>'Estado de México'],
            ['codigo_postal'=>'50200','colonia'=>'Campestre','municipio'=>'Toluca','estado'=>'Estado de México'],
            ['codigo_postal'=>'51000','colonia'=>'Centro','municipio'=>'Ciudad Nezahualcóyotl','estado'=>'Estado de México'],
            ['codigo_postal'=>'51010','colonia'=>'Progreso','municipio'=>'Ciudad Nezahualcóyotl','estado'=>'Estado de México'],
            ['codigo_postal'=>'51020','colonia'=>'Independencia','municipio'=>'Ciudad Nezahualcóyotl','estado'=>'Estado de México'],
            ['codigo_postal'=>'51030','colonia'=>'Juárez','municipio'=>'Ciudad Nezahualcóyotl','estado'=>'Estado de México'],
            ['codigo_postal'=>'51040','colonia'=>'San Juan','municipio'=>'Ciudad Nezahualcóyotl','estado'=>'Estado de México'],
            ['codigo_postal'=>'51050','colonia'=>'Los Ángeles','municipio'=>'Ciudad Nezahualcóyotl','estado'=>'Estado de México'],
            ['codigo_postal'=>'51060','colonia'=>'Lázaro Cárdenas','municipio'=>'Ciudad Nezahualcóyotl','estado'=>'Estado de México'],
            ['codigo_postal'=>'51070','colonia'=>'Benito Juárez','municipio'=>'Ciudad Nezahualcóyotl','estado'=>'Estado de México'],
            ['codigo_postal'=>'51080','colonia'=>'INFONAVIT','municipio'=>'Ciudad Nezahualcóyotl','estado'=>'Estado de México'],
            ['codigo_postal'=>'51090','colonia'=>'Miguel Hidalgo','municipio'=>'Ciudad Nezahualcóyotl','estado'=>'Estado de México'],
            ['codigo_postal'=>'52000','colonia'=>'Centro','municipio'=>'Ecatepec de Morelos','estado'=>'Estado de México'],
            ['codigo_postal'=>'52100','colonia'=>'San Cristóbal','municipio'=>'Ecatepec de Morelos','estado'=>'Estado de México'],
            ['codigo_postal'=>'52200','colonia'=>'San José','municipio'=>'Ecatepec de Morelos','estado'=>'Estado de México'],
            ['codigo_postal'=>'52300','colonia'=>'Lospirito','municipio'=>'Ecatepec de Morelos','estado'=>'Estado de México'],
            ['codigo_postal'=>'52400','colonia'=>'Ciudad Azteca','municipio'=>'Ecatepec de Morelos','estado'=>'Estado de México'],
            ['codigo_postal'=>'52500','colonia'=>'Jardines de Morelos','municipio'=>'Ecatepec de Morelos','estado'=>'Estado de México'],
            ['codigo_postal'=>'52600','colonia'=>'Loma Bonita','municipio'=>'Ecatepec de Morelos','estado'=>'Estado de México'],
            ['codigo_postal'=>'52700','colonia'=>'Las Américas','municipio'=>'Ecatepec de Morelos','estado'=>'Estado de México'],
            ['codigo_postal'=>'52800','colonia'=>'Buenavista','municipio'=>'Ecatepec de Morelos','estado'=>'Estado de México'],
            ['codigo_postal'=>'52900','colonia'=>'Valle de Anáhuac','municipio'=>'Ecatepec de Morelos','estado'=>'Estado de México'],
            ['codigo_postal'=>'53000','colonia'=>'Centro','municipio'=>'Naucalpan de Juárez','estado'=>'Estado de México'],
            ['codigo_postal'=>'53100','colonia'=>'San Andrés','municipio'=>'Naucalpan de Juárez','estado'=>'Estado de México'],
            ['codigo_postal'=>'53200','colonia'=>'San Pedro','municipio'=>'Naucalpan de Juárez','estado'=>'Estado de México'],
            ['codigo_postal'=>'53300','colonia'=>'Santa Cruz','municipio'=>'Naucalpan de Juárez','estado'=>'Estado de México'],
            ['codigo_postal'=>'53400','colonia'=>'Santa Ana','municipio'=>'Naucalpan de Juárez','estado'=>'Estado de México'],
            ['codigo_postal'=>'53500','colonia'=>'San Juan','municipio'=>'Naucalpan de Juárez','estado'=>'Estado de México'],
            ['codigo_postal'=>'53600','colonia'=>'Los Ángeles','municipio'=>'Naucalpan de Juárez','estado'=>'Estado de México'],
            ['codigo_postal'=>'53700','colonia'=>'INFONAVIT','municipio'=>'Naucalpan de Juárez','estado'=>'Estado de México'],
            ['codigo_postal'=>'53800','colonia'=>'Reforma','municipio'=>'Naucalpan de Juárez','estado'=>'Estado de México'],
            ['codigo_postal'=>'53900','colonia'=>'Independencia','municipio'=>'Naucalpan de Juárez','estado'=>'Estado de México'],
            ['codigo_postal'=>'54000','colonia'=>'Centro','municipio'=>'Tlalnepantla de Baz','estado'=>'Estado de México'],
            ['codigo_postal'=>'54100','colonia'=>'San Juan','municipio'=>'Tlalnepantla de Baz','estado'=>'Estado de México'],
            ['codigo_postal'=>'54200','colonia'=>'San Pedro','municipio'=>'Tlalnepantla de Baz','estado'=>'Estado de México'],
            ['codigo_postal'=>'54300','colonia'=>'San Mateo','municipio'=>'Tlalnepantla de Baz','estado'=>'Estado de México'],
            ['codigo_postal'=>'54400','colonia'=>'Santa Cruz','municipio'=>'Tlalnepantla de Baz','estado'=>'Estado de México'],
            ['codigo_postal'=>'54500','colonia'=>'Santa María','municipio'=>'Tlalnepantla de Baz','estado'=>'Estado de México'],
            ['codigo_postal'=>'54600','colonia'=>'Santiago','municipio'=>'Tlalnepantla de Baz','estado'=>'Estado de México'],
            ['codigo_postal'=>'54700','colonia'=>'Santo Domingo','municipio'=>'Tlalnepantla de Baz','estado'=>'Estado de México'],
            ['codigo_postal'=>'54800','colonia'=>'La Luz','municipio'=>'Tlalnepantla de Baz','estado'=>'Estado de México'],
            ['codigo_postal'=>'54900','colonia'=>'San Agustín','municipio'=>'Tlalnepantla de Baz','estado'=>'Estado de México'],
            ['codigo_postal'=>'55000','colonia'=>'Centro','municipio'=>'Metepec','estado'=>'Estado de México'],
            ['codigo_postal'=>'55100','colonia'=>'San Miguel','municipio'=>'Metepec','estado'=>'Estado de México'],
            ['codigo_postal'=>'55200','colonia'=>'San Pablo','municipio'=>'Metepec','estado'=>'Estado de México'],
            ['codigo_postal'=>'55300','colonia'=>'Santa Cruz','municipio'=>'Metepec','estado'=>'Estado de México'],
            ['codigo_postal'=>'55400','colonia'=>'Santiago','municipio'=>'Metepec','estado'=>'Estado de México'],
            ['codigo_postal'=>'55500','colonia'=>'San Pedro','municipio'=>'Metepec','estado'=>'Estado de México'],
            ['codigo_postal'=>'55600','colonia'=>'Los Reyes','municipio'=>'Metepec','estado'=>'Estado de México'],
            ['codigo_postal'=>'55700','colonia'=>'San Juan','municipio'=>'Metepec','estado'=>'Estado de México'],
            ['codigo_postal'=>'55800','colonia'=>'Santa María','municipio'=>'Metepec','estado'=>'Estado de México'],
            ['codigo_postal'=>'55900','colonia'=>'San Baltasar','municipio'=>'Metepec','estado'=>'Estado de México'],
            ['codigo_postal'=>'56000','colonia'=>'Centro','municipio'=>'Xochimilco','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'56100','colonia'=>'San Andrés','municipio'=>'Xochimilco','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'56200','colonia'=>'San Gregorio','municipio'=>'Xochimilco','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'56300','colonia'=>'San Lucas','municipio'=>'Xochimilco','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'56400','colonia'=>'San Mateo','municipio'=>'Xochimilco','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'56500','colonia'=>'San Miguel','municipio'=>'Xochimilco','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'56600','colonia'=>'San Pablo','municipio'=>'Xochimilco','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'56700','colonia'=>'San Pedro','municipio'=>'Xochimilco','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'56800','colonia'=>'Santa Cruz','municipio'=>'Xochimilco','estado'=>'Ciudad de México'],
            ['codigo_postal'=>'56900','colonia'=>'Santa María','municipio'=>'Xochimilco','estado'=>'Ciudad de México'],

            // Guanajuato
            ['codigo_postal'=>'36000','colonia'=>'Centro','municipio'=>'León','estado'=>'Guanajuato'],
            ['codigo_postal'=>'36010','colonia'=>'San Juan de Dios','municipio'=>'León','estado'=>'Guanajuato'],
            ['codigo_postal'=>'36020','colonia'=>'San Sebastián','municipio'=>'León','estado'=>'Guanajuato'],
            ['codigo_postal'=>'36030','colonia'=>'San Francisco','municipio'=>'León','estado'=>'Guanajuato'],
            ['codigo_postal'=>'36040','colonia'=>'San Miguel','municipio'=>'León','estado'=>'Guanajuato'],
            ['codigo_postal'=>'36050','colonia'=>'San Pablo','municipio'=>'León','estado'=>'Guanajuato'],
            ['codigo_postal'=>'36060','colonia'=>'Santa Cruz','municipio'=>'León','estado'=>'Guanajuato'],
            ['codigo_postal'=>'36070','colonia'=>'Santiago','municipio'=>'León','estado'=>'Guanajuato'],
            ['codigo_postal'=>'36080','colonia'=>'Santo Domingo','municipio'=>'León','estado'=>'Guanajuato'],
            ['codigo_postal'=>'36090','colonia'=>'La Soledad','municipio'=>'León','estado'=>'Guanajuato'],
            ['codigo_postal'=>'36100','colonia'=>'San José','municipio'=>'León','estado'=>'Guanajuato'],
            ['codigo_postal'=>'36200','colonia'=>'Centro','municipio'=>'Irapuato','estado'=>'Guanajuato'],
            ['codigo_postal'=>'36300','colonia'=>'Centro','municipio'=>'Celaya','estado'=>'Guanajuato'],
            ['codigo_postal'=>'36400','colonia'=>'Centro','municipio'=>'Salamanca','estado'=>'Guanajuato'],
            ['codigo_postal'=>'36500','colonia'=>'Centro','municipio'=>'Silao','estado'=>'Guanajuato'],
            ['codigo_postal'=>'36600','colonia'=>'Centro','municipio'=>'San Miguel de Allende','estado'=>'Guanajuato'],
            ['codigo_postal'=>'36700','colonia'=>'Centro','municipio'=>'Dolores Hidalgo','estado'=>'Guanajuato'],
            ['codigo_postal'=>'36800','colonia'=>'Centro','municipio'=>'Guanajuato','estado'=>'Guanajuato'],

            // Guerrero
            ['codigo_postal'=>'39000','colonia'=>'Centro','municipio'=>'Acapulco de Juárez','estado'=>'Guerrero'],
            ['codigo_postal'=>'39100','colonia'=>'Renacimiento','municipio'=>'Acapulco de Juárez','estado'=>'Guerrero'],
            ['codigo_postal'=>'39200','colonia'=>'Las Playas','municipio'=>'Acapulco de Juárez','estado'=>'Guerrero'],
            ['codigo_postal'=>'39300','colonia'=>'Diamante','municipio'=>'Acapulco de Juárez','estado'=>'Guerrero'],
            ['codigo_postal'=>'39400','colonia'=>'Pie de la Cuesta','municipio'=>'Acapulco de Juárez','estado'=>'Guerrero'],
            ['codigo_postal'=>'39500','colonia'=>'San Andrés','municipio'=>'Acapulco de Juárez','estado'=>'Guerrero'],
            ['codigo_postal'=>'39600','colonia'=>'Aeropuerto','municipio'=>'Acapulco de Juárez','estado'=>'Guerrero'],
            ['codigo_postal'=>'39700','colonia'=>'Tilapa','municipio'=>'Acapulco de Juárez','estado'=>'Guerrero'],
            ['codigo_postal'=>'39800','colonia'=>'Mango','municipio'=>'Acapulco de Juárez','estado'=>'Guerrero'],
            ['codigo_postal'=>'39900','colonia'=>'La Sabana','municipio'=>'Acapulco de Juárez','estado'=>'Guerrero'],
            ['codigo_postal'=>'40000','colonia'=>'Centro','municipio'=>'Chilpancingo de los Bravo','estado'=>'Guerrero'],
            ['codigo_postal'=>'41000','colonia'=>'Centro','municipio'=>'Iguala de la Independencia','estado'=>'Guerrero'],
            ['codigo_postal'=>'42000','colonia'=>'Centro','municipio'=>'Zihuatanejo de Azueta','estado'=>'Guerrero'],
            ['codigo_postal'=>'43000','colonia'=>'Centro','municipio'=>'Taxco de Alarcón','estado'=>'Guerrero'],

            // Hidalgo
            ['codigo_postal'=>'42000','colonia'=>'Centro','municipio'=>'Pachuca de Soto','estado'=>'Hidalgo'],
            ['codigo_postal'=>'42010','colonia'=>'San Juan','municipio'=>'Pachuca de Soto','estado'=>'Hidalgo'],
            ['codigo_postal'=>'42020','colonia'=>'San Pedro','municipio'=>'Pachuca de Soto','estado'=>'Hidalgo'],
            ['codigo_postal'=>'42030','colonia'=>'Santa María','municipio'=>'Pachuca de Soto','estado'=>'Hidalgo'],
            ['codigo_postal'=>'42040','colonia'=>'San Miguel','municipio'=>'Pachuca de Soto','estado'=>'Hidalgo'],
            ['codigo_postal'=>'42050','colonia'=>'Reforma','municipio'=>'Pachuca de Soto','estado'=>'Hidalgo'],
            ['codigo_postal'=>'42060','colonia'=>'Independencia','municipio'=>'Pachuca de Soto','estado'=>'Hidalgo'],
            ['codigo_postal'=>'42070','colonia'=>'Progreso','municipio'=>'Pachuca de Soto','estado'=>'Hidalgo'],
            ['codigo_postal'=>'42080','colonia'=>'INFONAVIT','municipio'=>'Pachuca de Soto','estado'=>'Hidalgo'],
            ['codigo_postal'=>'42090','colonia'=>'Los Ángeles','municipio'=>'Pachuca de Soto','estado'=>'Hidalgo'],
            ['codigo_postal'=>'42100','colonia'=>'Centro','municipio'=>'Tulancingo de Bravo','estado'=>'Hidalgo'],
            ['codigo_postal'=>'42200','colonia'=>'Centro','municipio'=>'Pachuca','estado'=>'Hidalgo'],
            ['codigo_postal'=>'43000','colonia'=>'Centro','municipio'=>'Tizayuca','estado'=>'Hidalgo'],
            ['codigo_postal'=>'43500','colonia'=>'Centro','municipio'=>'Tepeji del Río','estado'=>'Hidalgo'],
            ['codigo_postal'=>'44000','colonia'=>'Centro','municipio'=>'Huejutla de Reyes','estado'=>'Hidalgo'],

            // Jalisco
            ['codigo_postal'=>'44100','colonia'=>'Centro','municipio'=>'Guadalajara','estado'=>'Jalisco'],
            ['codigo_postal'=>'44110','colonia'=>'San Juan de Dios','municipio'=>'Guadalajara','estado'=>'Jalisco'],
            ['codigo_postal'=>'44120','colonia'=>'Mercado','municipio'=>'Guadalajara','estado'=>'Jalisco'],
            ['codigo_postal'=>'44130','colonia'=>'San José de Gracia','municipio'=>'Guadalajara','estado'=>'Jalisco'],
            ['codigo_postal'=>'44140','colonia'=>'Sagrada Familia','municipio'=>'Guadalajara','estado'=>'Jalisco'],
            ['codigo_postal'=>'44150','colonia'=>'Santa Mónica','municipio'=>'Guadalajara','estado'=>'Jalisco'],
            ['codigo_postal'=>'44160','colonia'=>'Analco','municipio'=>'Guadalajara','estado'=>'Jalisco'],
            ['codigo_postal'=>'44170','colonia'=>'Chapultepec','municipio'=>'Guadalajara','estado'=>'Jalisco'],
            ['codigo_postal'=>'44180','colonia'=>'Lafayette','municipio'=>'Guadalajara','estado'=>'Jalisco'],
            ['codigo_postal'=>'44190','colonia'=>'Moderna','municipio'=>'Guadalajara','estado'=>'Jalisco'],
            ['codigo_postal'=>'44200','colonia'=>'Americana','municipio'=>'Guadalajara','estado'=>'Jalisco'],
            ['codigo_postal'=>'44210','colonia'=>'Vista Hermosa','municipio'=>'Guadalajara','estado'=>'Jalisco'],
            ['codigo_postal'=>'44220','colonia'=>'Ladrilleras','municipio'=>'Guadalajara','estado'=>'Jalisco'],
            ['codigo_postal'=>'44230','colonia'=>'La Calzada','municipio'=>'Guadalajara','estado'=>'Jalisco'],
            ['codigo_postal'=>'44240','colonia'=>'Jardines','municipio'=>'Guadalajara','estado'=>'Jalisco'],
            ['codigo_postal'=>'44250','colonia'=>'INFONAVIT','municipio'=>'Guadalajara','estado'=>'Jalisco'],
            ['codigo_postal'=>'44260','colonia'=>'Mirador','municipio'=>'Guadalajara','estado'=>'Jalisco'],
            ['codigo_postal'=>'44270','colonia'=>'Reparto','municipio'=>'Guadalajara','estado'=>'Jalisco'],
            ['codigo_postal'=>'44280','colonia'=>'Cerro del 4','municipio'=>'Guadalajara','estado'=>'Jalisco'],
            ['codigo_postal'=>'44290','colonia'=>'El Bajío','municipio'=>'Guadalajara','estado'=>'Jalisco'],
            ['codigo_postal'=>'44300','colonia'=>'La Normal','municipio'=>'Guadalajara','estado'=>'Jalisco'],
            ['codigo_postal'=>'44310','colonia'=>'Tlaquepaque Centro','municipio'=>'Tlaquepaque','estado'=>'Jalisco'],
            ['codigo_postal'=>'44320','colonia'=>'San Juan','municipio'=>'Tlaquepaque','estado'=>'Jalisco'],
            ['codigo_postal'=>'44330','colonia'=>'San Pedro','municipio'=>'Tlaquepaque','estado'=>'Jalisco'],
            ['codigo_postal'=>'44340','colonia'=>'Santiago','municipio'=>'Tlaquepaque','estado'=>'Jalisco'],
            ['codigo_postal'=>'44350','colonia'=>'Santa Cruz','municipio'=>'Tlaquepaque','estado'=>'Jalisco'],
            ['codigo_postal'=>'44360','colonia'=>'El Sauz','municipio'=>'Tlaquepaque','estado'=>'Jalisco'],
            ['codigo_postal'=>'44370','colonia'=>'Mezquitán','municipio'=>'Guadalajara','estado'=>'Jalisco'],
            ['codigo_postal'=>'44380','colonia'=>'Huentitán','municipio'=>'Guadalajara','estado'=>'Jalisco'],
            ['codigo_postal'=>'44390','colonia'=>'Belén','municipio'=>'Guadalajara','estado'=>'Jalisco'],
            ['codigo_postal'=>'44400','colonia'=>'San Juan de Dios','municipio'=>'Guadalajara','estado'=>'Jalisco'],
            ['codigo_postal'=>'44410','colonia'=>'Zapopan Centro','municipio'=>'Zapopan','estado'=>'Jalisco'],
            ['codigo_postal'=>'44420','colonia'=>'San Andrés','municipio'=>'Zapopan','estado'=>'Jalisco'],
            ['codigo_postal'=>'44430','colonia'=>'San Sebastián','municipio'=>'Zapopan','estado'=>'Jalisco'],
            ['codigo_postal'=>'44440','colonia'=>'Santa María','municipio'=>'Zapopan','estado'=>'Jalisco'],
            ['codigo_postal'=>'44450','colonia'=>'Puerta de Hierro','municipio'=>'Zapopan','estado'=>'Jalisco'],
            ['codigo_postal'=>'44460','colonia'=>'Los Arcos','municipio'=>'Zapopan','estado'=>'Jalisco'],
            ['codigo_postal'=>'44470','colonia'=>'Tonalá Centro','municipio'=>'Tonalá','estado'=>'Jalisco'],
            ['codigo_postal'=>'44480','colonia'=>'Tlaquepaque','municipio'=>'Tlaquepaque','estado'=>'Jalisco'],
            ['codigo_postal'=>'44490','colonia'=>'Tlajomulco de Zúñiga','municipio'=>'Tlajomulco de Zúñiga','estado'=>'Jalisco'],
            ['codigo_postal'=>'44500','colonia'=>'El Salto Centro','municipio'=>'El Salto','estado'=>'Jalisco'],
            ['codigo_postal'=>'45000','colonia'=>'Centro','municipio'=>'Zapopan','estado'=>'Jalisco'],
            ['codigo_postal'=>'45100','colonia'=>'Chapalita','municipio'=>'Zapopan','estado'=>'Jalisco'],
            ['codigo_postal'=>'45200','colonia'=>'Ciudad del Sol','municipio'=>'Zapopan','estado'=>'Jalisco'],
            ['codigo_postal'=>'45300','colonia'=>'Santa Fe','municipio'=>'Zapopan','estado'=>'Jalisco'],
            ['codigo_postal'=>'45400','colonia'=>'La Cantera','municipio'=>'Zapopan','estado'=>'Jalisco'],
            ['codigo_postal'=>'46000','colonia'=>'Centro','municipio'=>'Puerto Vallarta','estado'=>'Jalisco'],
            ['codigo_postal'=>'46100','colonia'=>'Versalles','municipio'=>'Puerto Vallarta','estado'=>'Jalisco'],
            ['codigo_postal'=>'46200','colonia'=>'5 de Diciembre','municipio'=>'Puerto Vallarta','estado'=>'Jalisco'],
            ['codigo_postal'=>'46300','colonia'=>'Las Varas','municipio'=>'Puerto Vallarta','estado'=>'Jalisco'],
            ['codigo_postal'=>'46400','colonia'=>'Hotel Zone','municipio'=>'Puerto Vallarta','estado'=>'Jalisco'],

            // Michoacán
            ['codigo_postal'=>'58000','colonia'=>'Centro','municipio'=>'Morelia','estado'=>'Michoacán'],
            ['codigo_postal'=>'58010','colonia'=>'San Juan','municipio'=>'Morelia','estado'=>'Michoacán'],
            ['codigo_postal'=>'58020','colonia'=>'San Diego','municipio'=>'Morelia','estado'=>'Michoacán'],
            ['codigo_postal'=>'58030','colonia'=>'San Sebastián','municipio'=>'Morelia','estado'=>'Michoacán'],
            ['codigo_postal'=>'58040','colonia'=>'San Miguel','municipio'=>'Morelia','estado'=>'Michoacán'],
            ['codigo_postal'=>'58050','colonia'=>'San José','municipio'=>'Morelia','estado'=>'Michoacán'],
            ['codigo_postal'=>'58060','colonia'=>'San Pedro','municipio'=>'Morelia','estado'=>'Michoacán'],
            ['codigo_postal'=>'58070','colonia'=>'San Pablo','municipio'=>'Morelia','estado'=>'Michoacán'],
            ['codigo_postal'=>'58080','colonia'=>'San Juanico','municipio'=>'Morelia','estado'=>'Michoacán'],
            ['codigo_postal'=>'58090','colonia'=>'San Agustín','municipio'=>'Morelia','estado'=>'Michoacán'],
            ['codigo_postal'=>'58100','colonia'=>'Centro','municipio'=>'Uruapan','estado'=>'Michoacán'],
            ['codigo_postal'=>'58200','colonia'=>'Centro','municipio'=>'Lázaro Cárdenas','estado'=>'Michoacán'],
            ['codigo_postal'=>'58300','colonia'=>'Centro','municipio'=>'Zamora','estado'=>'Michoacán'],
            ['codigo_postal'=>'58400','colonia'=>'Centro','municipio'=>'Pátzcuaro','estado'=>'Michoacán'],
            ['codigo_postal'=>'58500','colonia'=>'Centro','municipio'=>'Apatzingán','estado'=>'Michoacán'],

            // Morelos
            ['codigo_postal'=>'62000','colonia'=>'Centro','municipio'=>'Cuernavaca','estado'=>'Morelos'],
            ['codigo_postal'=>'62010','colonia'=>'San Antonio','municipio'=>'Cuernavaca','estado'=>'Morelos'],
            ['codigo_postal'=>'62020','colonia'=>'San Juan','municipio'=>'Cuernavaca','estado'=>'Morelos'],
            ['codigo_postal'=>'62030','colonia'=>'San Miguel','municipio'=>'Cuernavaca','estado'=>'Morelos'],
            ['codigo_postal'=>'62040','colonia'=>'San Pablo','municipio'=>'Cuernavaca','estado'=>'Morelos'],
            ['codigo_postal'=>'62050','colonia'=>'Santa María','municipio'=>'Cuernavaca','estado'=>'Morelos'],
            ['codigo_postal'=>'62060','colonia'=>'Santiago','municipio'=>'Cuernavaca','estado'=>'Morelos'],
            ['codigo_postal'=>'62070','colonia'=>'Santo Domingo','municipio'=>'Cuernavaca','estado'=>'Morelos'],
            ['codigo_postal'=>'62080','colonia'=>'Vista Hermosa','municipio'=>'Cuernavaca','estado'=>'Morelos'],
            ['codigo_postal'=>'62090','colonia'=>'Las Palmas','municipio'=>'Cuernavaca','estado'=>'Morelos'],
            ['codigo_postal'=>'62100','colonia'=>'Centro','municipio'=>'Cuautla','estado'=>'Morelos'],
            ['codigo_postal'=>'62200','colonia'=>'Centro','municipio'=>'Jiutepec','estado'=>'Morelos'],
            ['codigo_postal'=>'62300','colonia'=>'Centro','municipio'=>'Temixco','estado'=>'Morelos'],
            ['codigo_postal'=>'62400','colonia'=>'Centro','municipio'=>'Tepoztlán','estado'=>'Morelos'],
            ['codigo_postal'=>'62500','colonia'=>'Centro','municipio'=>'Yautepec','estado'=>'Morelos'],
            ['codigo_postal'=>'62600','colonia'=>'Centro','municipio'=>'Xochitepec','estado'=>'Morelos'],
            ['codigo_postal'=>'62700','colonia'=>'Centro','municipio'=>'Emiliano Zapata','estado'=>'Morelos'],
            ['codigo_postal'=>'62800','colonia'=>'Centro','municipio'=>'Huitzilac','estado'=>'Morelos'],

            // Nuevo León
            ['codigo_postal'=>'64000','colonia'=>'Centro','municipio'=>'Monterrey','estado'=>'Nuevo León'],
            ['codigo_postal'=>'64010','colonia'=>'San Pedro','municipio'=>'Monterrey','estado'=>'Nuevo León'],
            ['codigo_postal'=>'64020','colonia'=>'San Jerónimo','municipio'=>'Monterrey','estado'=>'Nuevo León'],
            ['codigo_postal'=>'64030','colonia'=>'San Sebastián','municipio'=>'Monterrey','estado'=>'Nuevo León'],
            ['codigo_postal'=>'64040','colonia'=>'San Nicolás','municipio'=>'San Nicolás de los Garza','estado'=>'Nuevo León'],
            ['codigo_postal'=>'64050','colonia'=>'San Bernabé','municipio'=>'San Nicolás de los Garza','estado'=>'Nuevo León'],
            ['codigo_postal'=>'64060','colonia'=>'Santa María','municipio'=>'San Nicolás de los Garza','estado'=>'Nuevo León'],
            ['codigo_postal'=>'64070','colonia'=>'Anáhuac','municipio'=>'San Nicolás de los Garza','estado'=>'Nuevo León'],
            ['codigo_postal'=>'64080','colonia'=>'Los Ángeles','municipio'=>'San Nicolás de los Garza','estado'=>'Nuevo León'],
            ['codigo_postal'=>'64090','colonia'=>'INFONAVIT','municipio'=>'San Nicolás de los Garza','estado'=>'Nuevo León'],
            ['codigo_postal'=>'64100','colonia'=>'Obispado','municipio'=>'Monterrey','estado'=>'Nuevo León'],
            ['codigo_postal'=>'64200','colonia'=>'Centro','municipio'=>'Guadalupe','estado'=>'Nuevo León'],
            ['codigo_postal'=>'64300','colonia'=>'Centro','municipio'=>'San Pedro Garza García','estado'=>'Nuevo León'],
            ['codigo_postal'=>'64400','colonia'=>'Centro','municipio'=>'Santa Catarina','estado'=>'Nuevo León'],
            ['codigo_postal'=>'64500','colonia'=>'Centro','municipio'=>'San Nicolás de los Garza','estado'=>'Nuevo León'],
            ['codigo_postal'=>'64600','colonia'=>'Centro','municipio'=>'Apodaca','estado'=>'Nuevo León'],
            ['codigo_postal'=>'64700','colonia'=>'Centro','municipio'=>'Escobedo','estado'=>'Nuevo León'],
            ['codigo_postal'=>'64800','colonia'=>'Centro','municipio'=>'García','estado'=>'Nuevo León'],
            ['codigo_postal'=>'64900','colonia'=>'Centro','municipio'=>'San Nicolás de los Garza','estado'=>'Nuevo León'],

            // Oaxaca
            ['codigo_postal'=>'68000','colonia'=>'Centro','municipio'=>'Oaxaca de Juárez','estado'=>'Oaxaca'],
            ['codigo_postal'=>'68010','colonia'=>'Jalatlaco','municipio'=>'Oaxaca de Juárez','estado'=>'Oaxaca'],
            ['codigo_postal'=>'68020','colonia'=>'Xochimilco','municipio'=>'Oaxaca de Juárez','estado'=>'Oaxaca'],
            ['codigo_postal'=>'68030','colonia'=>'San Felipe','municipio'=>'Oaxaca de Juárez','estado'=>'Oaxaca'],
            ['codigo_postal'=>'68040','colonia'=>'San Martín','municipio'=>'Oaxaca de Juárez','estado'=>'Oaxaca'],
            ['codigo_postal'=>'68050','colonia'=>'Santa Lucía','municipio'=>'Oaxaca de Juárez','estado'=>'Oaxaca'],
            ['codigo_postal'=>'68060','colonia'=>'La Noria','municipio'=>'Oaxaca de Juárez','estado'=>'Oaxaca'],
            ['codigo_postal'=>'68070','colonia'=>'Reforma','municipio'=>'Oaxaca de Juárez','estado'=>'Oaxaca'],
            ['codigo_postal'=>'68080','colonia'=>'San Juan','municipio'=>'Oaxaca de Juárez','estado'=>'Oaxaca'],
            ['codigo_postal'=>'68090','colonia'=>'Santa María','municipio'=>'Oaxaca de Juárez','estado'=>'Oaxaca'],
            ['codigo_postal'=>'68100','colonia'=>'Centro','municipio'=>'Puerto Escondido','estado'=>'Oaxaca'],
            ['codigo_postal'=>'68200','colonia'=>'Centro','municipio'=>'San Cristóbal de las Casas','estado'=>'Oaxaca'],
            ['codigo_postal'=>'68300','colonia'=>'Centro','municipio'=>'Juchitán de Zaragoza','estado'=>'Oaxaca'],

            // Puebla
            ['codigo_postal'=>'72000','colonia'=>'Centro','municipio'=>'Puebla','estado'=>'Puebla'],
            ['codigo_postal'=>'72010','colonia'=>'San Manuel','municipio'=>'Puebla','estado'=>'Puebla'],
            ['codigo_postal'=>'72020','colonia'=>'San Miguel','municipio'=>'Puebla','estado'=>'Puebla'],
            ['codigo_postal'=>'72030','colonia'=>'San Andrés','municipio'=>'Puebla','estado'=>'Puebla'],
            ['codigo_postal'=>'72040','colonia'=>'San José','municipio'=>'Puebla','estado'=>'Puebla'],
            ['codigo_postal'=>'72050','colonia'=>'Santa Cruz','municipio'=>'Puebla','estado'=>'Puebla'],
            ['codigo_postal'=>'72060','colonia'=>'San Felipe','municipio'=>'Puebla','estado'=>'Puebla'],
            ['codigo_postal'=>'72070','colonia'=>'Santiago','municipio'=>'Puebla','estado'=>'Puebla'],
            ['codigo_postal'=>'72080','colonia'=>'Santa Catarina','municipio'=>'Puebla','estado'=>'Puebla'],
            ['codigo_postal'=>'72090','colonia'=>'Santo Domingo','municipio'=>'Puebla','estado'=>'Puebla'],
            ['codigo_postal'=>'72100','colonia'=>'Loreto','municipio'=>'Puebla','estado'=>'Puebla'],
            ['codigo_postal'=>'72110','colonia'=>'San Miguelito','municipio'=>'Puebla','estado'=>'Puebla'],
            ['codigo_postal'=>'72120','colonia'=>'El Carmen','municipio'=>'Puebla','estado'=>'Puebla'],
            ['codigo_postal'=>'72130','colonia'=>'San Baltazar','municipio'=>'Puebla','estado'=>'Puebla'],
            ['codigo_postal'=>'72140','colonia'=>'San Cristóbal','municipio'=>'Puebla','estado'=>'Puebla'],
            ['codigo_postal'=>'72150','colonia'=>'San Gabriel','municipio'=>'Puebla','estado'=>'Puebla'],
            ['codigo_postal'=>'72160','colonia'=>'San Juan','municipio'=>'Puebla','estado'=>'Puebla'],
            ['codigo_postal'=>'72170','colonia'=>'San Lucas','municipio'=>'Puebla','estado'=>'Puebla'],
            ['codigo_postal'=>'72180','colonia'=>'San Mateo','municipio'=>'Puebla','estado'=>'Puebla'],
            ['codigo_postal'=>'72190','colonia'=>'San Pablo','municipio'=>'Puebla','estado'=>'Puebla'],
            ['codigo_postal'=>'72200','colonia'=>'La Paz','municipio'=>'Puebla','estado'=>'Puebla'],
            ['codigo_postal'=>'72210','colonia'=>'San Pedro','municipio'=>'Puebla','estado'=>'Puebla'],
            ['codigo_postal'=>'72220','colonia'=>'Santa Ana','municipio'=>'Puebla','estado'=>'Puebla'],
            ['codigo_postal'=>'72230','colonia'=>'Santa María','municipio'=>'Puebla','estado'=>'Puebla'],
            ['codigo_postal'=>'72240','colonia'=>'Santa Teresa','municipio'=>'Puebla','estado'=>'Puebla'],
            ['codigo_postal'=>'72250','colonia'=>'Vista Hermosa','municipio'=>'Puebla','estado'=>'Puebla'],
            ['codigo_postal'=>'72260','colonia'=>'Américas','municipio'=>'Puebla','estado'=>'Puebla'],
            ['codigo_postal'=>'72270','colonia'=>'INFONAVIT','municipio'=>'Puebla','estado'=>'Puebla'],
            ['codigo_postal'=>'72280','colonia'=>'Los Ángeles','municipio'=>'Puebla','estado'=>'Puebla'],
            ['codigo_postal'=>'72290','colonia'=>'Las Américas','municipio'=>'Puebla','estado'=>'Puebla'],
            ['codigo_postal'=>'72300','colonia'=>'Centro','municipio'=>'Cholula de Rivadavia','estado'=>'Puebla'],
            ['codigo_postal'=>'72400','colonia'=>'Centro','municipio'=>'Atlixco','estado'=>'Puebla'],
            ['codigo_postal'=>'72500','colonia'=>'Centro','municipio'=>'San Martín Texmelucan','estado'=>'Puebla'],
            ['codigo_postal'=>'72600','colonia'=>'Centro','municipio'=>'Tehuacán','estado'=>'Puebla'],

            // Querétaro
            ['codigo_postal'=>'76000','colonia'=>'Centro','municipio'=>'Querétaro','estado'=>'Querétaro'],
            ['codigo_postal'=>'76010','colonia'=>'San Juan','municipio'=>'Querétaro','estado'=>'Querétaro'],
            ['codigo_postal'=>'76020','colonia'=>'San Pedro','municipio'=>'Querétaro','estado'=>'Querétaro'],
            ['codigo_postal'=>'76030','colonia'=>'Santa Rosa','municipio'=>'Querétaro','estado'=>'Querétaro'],
            ['codigo_postal'=>'76040','colonia'=>'Santa María','municipio'=>'Querétaro','estado'=>'Querétaro'],
            ['codigo_postal'=>'76050','colonia'=>'San José','municipio'=>'Querétaro','estado'=>'Querétaro'],
            ['codigo_postal'=>'76060','colonia'=>'San Pablo','municipio'=>'Querétaro','estado'=>'Querétaro'],
            ['codigo_postal'=>'76070','colonia'=>'Santa Cruz','municipio'=>'Querétaro','estado'=>'Querétaro'],
            ['codigo_postal'=>'76080','colonia'=>'San Miguel','municipio'=>'Querétaro','estado'=>'Querétaro'],
            ['codigo_postal'=>'76090','colonia'=>'San Sebastián','municipio'=>'Querétaro','estado'=>'Querétaro'],
            ['codigo_postal'=>'76100','colonia'=>'La Peregrina','municipio'=>'Querétaro','estado'=>'Querétaro'],
            ['codigo_postal'=>'76110','colonia'=>'El Jardín','municipio'=>'Querétaro','estado'=>'Querétaro'],
            ['codigo_postal'=>'76120','colonia'=>'Centro Sur','municipio'=>'Querétaro','estado'=>'Querétaro'],
            ['codigo_postal'=>'76130','colonia'=>'Viveros','municipio'=>'Querétaro','estado'=>'Querétaro'],
            ['codigo_postal'=>'76140','colonia'=>'INFONAVIT','municipio'=>'Querétaro','estado'=>'Querétaro'],
            ['codigo_postal'=>'76150','colonia'=>'Las Américas','municipio'=>'Querétaro','estado'=>'Querétaro'],
            ['codigo_postal'=>'76160','colonia'=>'Los Ángeles','municipio'=>'Querétaro','estado'=>'Querétaro'],
            ['codigo_postal'=>'76170','colonia'=>'Vista Hermosa','municipio'=>'Querétaro','estado'=>'Querétaro'],
            ['codigo_postal'=>'76180','colonia'=>'Campestre','municipio'=>'Querétaro','estado'=>'Querétaro'],
            ['codigo_postal'=>'76190','colonia'=>'El Fuerte','municipio'=>'Querétaro','estado'=>'Querétaro'],
            ['codigo_postal'=>'76200','colonia'=>'Centro','municipio'=>'San Juan del Río','estado'=>'Querétaro'],
            ['codigo_postal'=>'76300','colonia'=>'Centro','municipio'=>'Corregidora','estado'=>'Querétaro'],
            ['codigo_postal'=>'76400','colonia'=>'Centro','municipio'=>'El Marqués','estado'=>'Querétaro'],

            // Quintana Roo
            ['codigo_postal'=>'77000','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77100','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77200','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77300','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77400','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77500','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77600','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77700','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77710','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77720','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77730','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77740','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77750','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77760','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77770','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77780','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77790','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77800','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77810','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77820','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77830','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77840','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77850','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77860','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77870','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77880','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77890','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77900','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77910','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77920','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77930','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77940','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77950','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77960','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77970','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77980','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77990','colonia'=>'Centro','municipio'=>'Benito Juárez','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77600','colonia'=>'Centro','municipio'=>'Solidaridad','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77710','colonia'=>'Centro','municipio'=>'Solidaridad','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77720','colonia'=>'Centro','municipio'=>'Solidaridad','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77730','colonia'=>'Centro','municipio'=>'Solidaridad','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77740','colonia'=>'Centro','municipio'=>'Solidaridad','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77750','colonia'=>'Centro','municipio'=>'Solidaridad','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77760','colonia'=>'Centro','municipio'=>'Solidaridad','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77770','colonia'=>'Centro','municipio'=>'Solidaridad','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77780','colonia'=>'Centro','municipio'=>'Solidaridad','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77790','colonia'=>'Centro','municipio'=>'Solidaridad','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77800','colonia'=>'Centro','municipio'=>'Solidaridad','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77810','colonia'=>'Centro','municipio'=>'Solidaridad','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77820','colonia'=>'Centro','municipio'=>'Solidaridad','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77830','colonia'=>'Centro','municipio'=>'Solidaridad','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77840','colonia'=>'Centro','municipio'=>'Solidaridad','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77850','colonia'=>'Centro','municipio'=>'Solidaridad','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77860','colonia'=>'Centro','municipio'=>'Solidaridad','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77870','colonia'=>'Centro','municipio'=>'Solidaridad','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77880','colonia'=>'Centro','municipio'=>'Solidaridad','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77890','colonia'=>'Centro','municipio'=>'Solidaridad','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77900','colonia'=>'Centro','municipio'=>'Solidaridad','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77910','colonia'=>'Centro','municipio'=>'Solidaridad','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77920','colonia'=>'Centro','municipio'=>'Solidaridad','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77930','colonia'=>'Centro','municipio'=>'Solidaridad','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77940','colonia'=>'Centro','municipio'=>'Solidaridad','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77950','colonia'=>'Centro','municipio'=>'Solidaridad','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77960','colonia'=>'Centro','municipio'=>'Solidaridad','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77970','colonia'=>'Centro','municipio'=>'Solidaridad','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77980','colonia'=>'Centro','municipio'=>'Solidaridad','estado'=>'Quintana Roo'],
            ['codigo_postal'=>'77990','colonia'=>'Centro','municipio'=>'Solidaridad','estado'=>'Quintana Roo'],

            // San Luis Potosí
            ['codigo_postal'=>'78000','colonia'=>'Centro','municipio'=>'San Luis Potosí','estado'=>'San Luis Potosí'],
            ['codigo_postal'=>'78010','colonia'=>'San Juan','municipio'=>'San Luis Potosí','estado'=>'San Luis Potosí'],
            ['codigo_postal'=>'78020','colonia'=>'San José','municipio'=>'San Luis Potosí','estado'=>'San Luis Potosí'],
            ['codigo_postal'=>'78030','colonia'=>'San Miguel','municipio'=>'San Luis Potosí','estado'=>'San Luis Potosí'],
            ['codigo_postal'=>'78040','colonia'=>'San Pedro','municipio'=>'San Luis Potosí','estado'=>'San Luis Potosí'],
            ['codigo_postal'=>'78050','colonia'=>'San Pablo','municipio'=>'San Luis Potosí','estado'=>'San Luis Potosí'],
            ['codigo_postal'=>'78060','colonia'=>'Santa Cruz','municipio'=>'San Luis Potosí','estado'=>'San Luis Potosí'],
            ['codigo_postal'=>'78070','colonia'=>'Santiago','municipio'=>'San Luis Potosí','estado'=>'San Luis Potosí'],
            ['codigo_postal'=>'78080','colonia'=>'Santo Domingo','municipio'=>'San Luis Potosí','estado'=>'San Luis Potosí'],
            ['codigo_postal'=>'78090','colonia'=>'San Francisco','municipio'=>'San Luis Potosí','estado'=>'San Luis Potosí'],
            ['codigo_postal'=>'78100','colonia'=>'San Agustín','municipio'=>'San Luis Potosí','estado'=>'San Luis Potosí'],
            ['codigo_postal'=>'78200','colonia'=>'Centro','municipio'=>'Soledad de Graciano Sánchez','estado'=>'San Luis Potosí'],
            ['codigo_postal'=>'78300','colonia'=>'Centro','municipio'=>'Matehuala','estado'=>'San Luis Potosí'],
            ['codigo_postal'=>'78400','colonia'=>'Centro','municipio'=>'Ciudad Valles','estado'=>'San Luis Potosí'],

            // Sinaloa
            ['codigo_postal'=>'80000','colonia'=>'Centro','municipio'=>'Culiacán','estado'=>'Sinaloa'],
            ['codigo_postal'=>'80010','colonia'=>'San Juan','municipio'=>'Culiacán','estado'=>'Sinaloa'],
            ['codigo_postal'=>'80020','colonia'=>'San Pedro','municipio'=>'Culiacán','estado'=>'Sinaloa'],
            ['codigo_postal'=>'80030','colonia'=>'San Miguel','municipio'=>'Culiacán','estado'=>'Sinaloa'],
            ['codigo_postal'=>'80040','colonia'=>'San José','municipio'=>'Culiacán','estado'=>'Sinaloa'],
            ['codigo_postal'=>'80050','colonia'=>'San Pablo','municipio'=>'Culiacán','estado'=>'Sinaloa'],
            ['codigo_postal'=>'80060','colonia'=>'Santa Cruz','municipio'=>'Culiacán','estado'=>'Sinaloa'],
            ['codigo_postal'=>'80070','colonia'=>'Santiago','municipio'=>'Culiacán','estado'=>'Sinaloa'],
            ['codigo_postal'=>'80080','colonia'=>'Santo Domingo','municipio'=>'Culiacán','estado'=>'Sinaloa'],
            ['codigo_postal'=>'80090','colonia'=>'La Luz','municipio'=>'Culiacán','estado'=>'Sinaloa'],
            ['codigo_postal'=>'81000','colonia'=>'Centro','municipio'=>'Mazatlán','estado'=>'Sinaloa'],
            ['codigo_postal'=>'81100','colonia'=>'Centro','municipio'=>'Mazatlán','estado'=>'Sinaloa'],
            ['codigo_postal'=>'81200','colonia'=>'Centro','municipio'=>'Mazatlán','estado'=>'Sinaloa'],
            ['codigo_postal'=>'81300','colonia'=>'Centro','municipio'=>'Mazatlán','estado'=>'Sinaloa'],
            ['codigo_postal'=>'81400','colonia'=>'Centro','municipio'=>'Mazatlán','estado'=>'Sinaloa'],
            ['codigo_postal'=>'81500','colonia'=>'Centro','municipio'=>'Mazatlán','estado'=>'Sinaloa'],
            ['codigo_postal'=>'81600','colonia'=>'Centro','municipio'=>'Mazatlán','estado'=>'Sinaloa'],
            ['codigo_postal'=>'81700','colonia'=>'Centro','municipio'=>'Mazatlán','estado'=>'Sinaloa'],
            ['codigo_postal'=>'81800','colonia'=>'Centro','municipio'=>'Mazatlán','estado'=>'Sinaloa'],
            ['codigo_postal'=>'81900','colonia'=>'Centro','municipio'=>'Mazatlán','estado'=>'Sinaloa'],
            ['codigo_postal'=>'82000','colonia'=>'Centro','municipio'=>'Los Mochis','estado'=>'Sinaloa'],
            ['codigo_postal'=>'83000','colonia'=>'Centro','municipio'=>'Guasave','estado'=>'Sinaloa'],
            ['codigo_postal'=>'84000','colonia'=>'Centro','municipio'=>'Navolato','estado'=>'Sinaloa'],

            // Sonora
            ['codigo_postal'=>'83000','colonia'=>'Centro','municipio'=>'Hermosillo','estado'=>'Sonora'],
            ['codigo_postal'=>'83100','colonia'=>'San Juan','municipio'=>'Hermosillo','estado'=>'Sonora'],
            ['codigo_postal'=>'83200','colonia'=>'San Pedro','municipio'=>'Hermosillo','estado'=>'Sonora'],
            ['codigo_postal'=>'83300','colonia'=>'San Miguel','municipio'=>'Hermosillo','estado'=>'Sonora'],
            ['codigo_postal'=>'83400','colonia'=>'San José','municipio'=>'Hermosillo','estado'=>'Sonora'],
            ['codigo_postal'=>'83500','colonia'=>'San Pablo','municipio'=>'Hermosillo','estado'=>'Sonora'],
            ['codigo_postal'=>'83600','colonia'=>'Santa Cruz','municipio'=>'Hermosillo','estado'=>'Sonora'],
            ['codigo_postal'=>'83700','colonia'=>'Santiago','municipio'=>'Hermosillo','estado'=>'Sonora'],
            ['codigo_postal'=>'83800','colonia'=>'Santo Domingo','municipio'=>'Hermosillo','estado'=>'Sonora'],
            ['codigo_postal'=>'83900','colonia'=>'La Luz','municipio'=>'Hermosillo','estado'=>'Sonora'],
            ['codigo_postal'=>'84000','colonia'=>'Centro','municipio'=>'Ciudad Obregón','estado'=>'Sonora'],
            ['codigo_postal'=>'85000','colonia'=>'Centro','municipio'=>'Nogales','estado'=>'Sonora'],
            ['codigo_postal'=>'86000','colonia'=>'Centro','municipio'=>'Agua Prieta','estado'=>'Sonora'],
            ['codigo_postal'=>'87000','colonia'=>'Centro','municipio'=>'Guaymas','estado'=>'Sonora'],
            ['codigo_postal'=>'88000','colonia'=>'Centro','municipio'=>'Empalme','estado'=>'Sonora'],

            // Tabasco
            ['codigo_postal'=>'86000','colonia'=>'Centro','municipio'=>'Villahermosa','estado'=>'Tabasco'],
            ['codigo_postal'=>'86010','colonia'=>'San Juan','municipio'=>'Villahermosa','estado'=>'Tabasco'],
            ['codigo_postal'=>'86020','colonia'=>'San Pedro','municipio'=>'Villahermosa','estado'=>'Tabasco'],
            ['codigo_postal'=>'86030','colonia'=>'San Miguel','municipio'=>'Villahermosa','estado'=>'Tabasco'],
            ['codigo_postal'=>'86040','colonia'=>'San José','municipio'=>'Villahermosa','estado'=>'Tabasco'],
            ['codigo_postal'=>'86050','colonia'=>'San Pablo','municipio'=>'Villahermosa','estado'=>'Tabasco'],
            ['codigo_postal'=>'86060','colonia'=>'Santa Cruz','municipio'=>'Villahermosa','estado'=>'Tabasco'],
            ['codigo_postal'=>'86070','colonia'=>'Santiago','municipio'=>'Villahermosa','estado'=>'Tabasco'],
            ['codigo_postal'=>'86080','colonia'=>'Santo Domingo','municipio'=>'Villahermosa','estado'=>'Tabasco'],
            ['codigo_postal'=>'86090','colonia'=>'La Luz','municipio'=>'Villahermosa','estado'=>'Tabasco'],
            ['codigo_postal'=>'86100','colonia'=>'Centro','municipio'=>'Cárdenas','estado'=>'Tabasco'],
            ['codigo_postal'=>'86200','colonia'=>'Centro','municipio'=>'Comalcalco','estado'=>'Tabasco'],
            ['codigo_postal'=>'86300','colonia'=>'Centro','municipio'=>'Huimanguillo','estado'=>'Tabasco'],
            ['codigo_postal'=>'86400','colonia'=>'Centro','municipio'=>'Macuspana','estado'=>'Tabasco'],

            // Tamaulipas
            ['codigo_postal'=>'87000','colonia'=>'Centro','municipio'=>'Tampico','estado'=>'Tamaulipas'],
            ['codigo_postal'=>'87010','colonia'=>'San Juan','municipio'=>'Tampico','estado'=>'Tamaulipas'],
            ['codigo_postal'=>'87020','colonia'=>'San Pedro','municipio'=>'Tampico','estado'=>'Tamaulipas'],
            ['codigo_postal'=>'87030','colonia'=>'San Miguel','municipio'=>'Tampico','estado'=>'Tamaulipas'],
            ['codigo_postal'=>'87040','colonia'=>'San José','municipio'=>'Tampico','estado'=>'Tamaulipas'],
            ['codigo_postal'=>'87050','colonia'=>'San Pablo','municipio'=>'Tampico','estado'=>'Tamaulipas'],
            ['codigo_postal'=>'87060','colonia'=>'Santa Cruz','municipio'=>'Tampico','estado'=>'Tamaulipas'],
            ['codigo_postal'=>'87070','colonia'=>'Santiago','municipio'=>'Tampico','estado'=>'Tamaulipas'],
            ['codigo_postal'=>'87080','colonia'=>'Santo Domingo','municipio'=>'Tampico','estado'=>'Tamaulipas'],
            ['codigo_postal'=>'87090','colonia'=>'La Luz','municipio'=>'Tampico','estado'=>'Tamaulipas'],
            ['codigo_postal'=>'88000','colonia'=>'Centro','municipio'=>'Ciudad Madero','estado'=>'Tamaulipas'],
            ['codigo_postal'=>'89000','colonia'=>'Centro','municipio'=>'Reynosa','estado'=>'Tamaulipas'],
            ['codigo_postal'=>'89100','colonia'=>'Centro','municipio'=>'Nuevo Laredo','estado'=>'Tamaulipas'],
            ['codigo_postal'=>'89200','colonia'=>'Centro','municipio'=>'Matamoros','estado'=>'Tamaulipas'],
            ['codigo_postal'=>'89300','colonia'=>'Centro','municipio'=>'Ciudad Victoria','estado'=>'Tamaulipas'],

            // Veracruz
            ['codigo_postal'=>'91000','colonia'=>'Centro','municipio'=>'Veracruz','estado'=>'Veracruz'],
            ['codigo_postal'=>'91010','colonia'=>'San Juan','municipio'=>'Veracruz','estado'=>'Veracruz'],
            ['codigo_postal'=>'91020','colonia'=>'San Pedro','municipio'=>'Veracruz','estado'=>'Veracruz'],
            ['codigo_postal'=>'91030','colonia'=>'San Miguel','municipio'=>'Veracruz','estado'=>'Veracruz'],
            ['codigo_postal'=>'91040','colonia'=>'San José','municipio'=>'Veracruz','estado'=>'Veracruz'],
            ['codigo_postal'=>'91050','colonia'=>'San Pablo','municipio'=>'Veracruz','estado'=>'Veracruz'],
            ['codigo_postal'=>'91060','colonia'=>'Santa Cruz','municipio'=>'Veracruz','estado'=>'Veracruz'],
            ['codigo_postal'=>'91070','colonia'=>'Santiago','municipio'=>'Veracruz','estado'=>'Veracruz'],
            ['codigo_postal'=>'91080','colonia'=>'Santo Domingo','municipio'=>'Veracruz','estado'=>'Veracruz'],
            ['codigo_postal'=>'91090','colonia'=>'La Luz','municipio'=>'Veracruz','estado'=>'Veracruz'],
            ['codigo_postal'=>'91100','colonia'=>'Centro','municipio'=>'Orizaba','estado'=>'Veracruz'],
            ['codigo_postal'=>'91200','colonia'=>'Centro','municipio'=>'Córdoba','estado'=>'Veracruz'],
            ['codigo_postal'=>'91300','colonia'=>'Centro','municipio'=>'Minatitlán','estado'=>'Veracruz'],
            ['codigo_postal'=>'91400','colonia'=>'Centro','municipio'=>'Coatzacoalcos','estado'=>'Veracruz'],
            ['codigo_postal'=>'91500','colonia'=>'Centro','municipio'=>'Xalapa','estado'=>'Veracruz'],
            ['codigo_postal'=>'91600','colonia'=>'Centro','municipio'=>'Boca del Río','estado'=>'Veracruz'],
            ['codigo_postal'=>'91700','colonia'=>'Centro','municipio'=>'Poza Rica de Hidalgo','estado'=>'Veracruz'],
            ['codigo_postal'=>'91800','colonia'=>'Centro','municipio'=>'Martínez de la Torre','estado'=>'Veracruz'],
            ['codigo_postal'=>'91900','colonia'=>'Centro','municipio'=>'Catemaco','estado'=>'Veracruz'],

            // Yucatán
            ['codigo_postal'=>'97000','colonia'=>'Centro','municipio'=>'Mérida','estado'=>'Yucatán'],
            ['codigo_postal'=>'97010','colonia'=>'San Juan','municipio'=>'Mérida','estado'=>'Yucatán'],
            ['codigo_postal'=>'97020','colonia'=>'San Pedro','municipio'=>'Mérida','estado'=>'Yucatán'],
            ['codigo_postal'=>'97030','colonia'=>'San Miguel','municipio'=>'Mérida','estado'=>'Yucatán'],
            ['codigo_postal'=>'97040','colonia'=>'San José','municipio'=>'Mérida','estado'=>'Yucatán'],
            ['codigo_postal'=>'97050','colonia'=>'San Pablo','municipio'=>'Mérida','estado'=>'Yucatán'],
            ['codigo_postal'=>'97060','colonia'=>'Santa Cruz','municipio'=>'Mérida','estado'=>'Yucatán'],
            ['codigo_postal'=>'97070','colonia'=>'Santiago','municipio'=>'Mérida','estado'=>'Yucatán'],
            ['codigo_postal'=>'97080','colonia'=>'Santo Domingo','municipio'=>'Mérida','estado'=>'Yucatán'],
            ['codigo_postal'=>'97090','colonia'=>'La Luz','municipio'=>'Mérida','estado'=>'Yucatán'],
            ['codigo_postal'=>'97100','colonia'=>'Centro','municipio'=>'Valladolid','estado'=>'Yucatán'],
            ['codigo_postal'=>'97200','colonia'=>'Centro','municipio'=>'Izamal','estado'=>'Yucatán'],
            ['codigo_postal'=>'97300','colonia'=>'Centro','municipio'=>'Tizimín','estado'=>'Yucatán'],

            // Zacatecas
            ['codigo_postal'=>'98000','colonia'=>'Centro','municipio'=>'Zacatecas','estado'=>'Zacatecas'],
            ['codigo_postal'=>'98010','colonia'=>'San Juan','municipio'=>'Zacatecas','estado'=>'Zacatecas'],
            ['codigo_postal'=>'98020','colonia'=>'San Pedro','municipio'=>'Zacatecas','estado'=>'Zacatecas'],
            ['codigo_postal'=>'98030','colonia'=>'San Miguel','municipio'=>'Zacatecas','estado'=>'Zacatecas'],
            ['codigo_postal'=>'98040','colonia'=>'San José','municipio'=>'Zacatecas','estado'=>'Zacatecas'],
            ['codigo_postal'=>'98050','colonia'=>'San Pablo','municipio'=>'Zacatecas','estado'=>'Zacatecas'],
            ['codigo_postal'=>'98060','colonia'=>'Santa Cruz','municipio'=>'Zacatecas','estado'=>'Zacatecas'],
            ['codigo_postal'=>'98070','colonia'=>'Santiago','municipio'=>'Zacatecas','estado'=>'Zacatecas'],
            ['codigo_postal'=>'98080','colonia'=>'Santo Domingo','municipio'=>'Zacatecas','estado'=>'Zacatecas'],
            ['codigo_postal'=>'98090','colonia'=>'La Luz','municipio'=>'Zacatecas','estado'=>'Zacatecas'],
            ['codigo_postal'=>'99000','colonia'=>'Centro','municipio'=>'Fresnillo','estado'=>'Zacatecas'],
            ['codigo_postal'=>'99100','colonia'=>'Centro','municipio'=>'Guadalupe','estado'=>'Zacatecas'],
            ['codigo_postal'=>'99200','colonia'=>'Centro','municipio'=>'Jerez','estado'=>'Zacatecas'],
            ['codigo_postal'=>'99300','colonia'=>'Centro','municipio'=>'Sombrerete','estado'=>'Zacatecas'],
        ];

        DB::table('colonias')->insert($data);
    }
}
